name: Release

on: 
  workflow_dispatch:
    inputs:
      release_enabled:
        description: "Release the package to PyPI"
        required: true
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        pip --version

    - name: Install hatch
      run: |
        pip install hatch
        hatch --version

    - name: Build package
      run: |
        hatch build

    - name: Publish package on PyPI
      if: ${{ inputs.release_enabled }}
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}

    - name: Publish the release notes
      if: ${{ inputs.release_enabled }}
      uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
      with:
        publish: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check PyPI package installation
      if: ${{ inputs.release_enabled }}
      run: |
        sleep 120 &&
        version=$(hatch -q version) &&
        pip install \
        thunderpath==$version &&
        pip list | grep thunderpath
